package hdt8;

import java.io.FileReader;
import java.util.Scanner;

/**
 * @author Alexis Hengstenberg 17699
 * @author Sebastian Arriola 11463
 */
public class CVista extends javax.swing.JFrame 
{
    protected PriorityQueue<CPaciente> queue;
    /**
     * Creates new form CVista
     */
    public CVista() {
        initComponents();
        queue = new CVectorHeap<>();
        readFileAndFillQueue("src/pacientes.txt");
        jLbl_PacientesRestantes.setText("Pacientes restantes: " + queue.size());
    }
    
    protected void readFileAndFillQueue(String filePath)
    {
        Scanner s = null;
        try
        {
            s = new Scanner(new FileReader(filePath));
            while(s.hasNextLine())
            {
                String[] parts = s.nextLine().split(",");
                if(parts.length < 3) continue; // bad patient format
                queue.add(new CPaciente(parts[0], parts[1], parts[2]));
            }
        }
        catch(Exception e) { System.out.println(e.getMessage()); }
        finally
        {
            if(s != null) s.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtn_AtenderSiguiente = new javax.swing.JButton();
        jLbl_PacientesRestantes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtArea_Pacientes = new javax.swing.JTextArea();
        jLbl_PacientesAtendidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital \"El muertito\" - VectorHeap");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtn_AtenderSiguiente.setText("Atender Siguiente Paciente");
        jBtn_AtenderSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_AtenderSiguienteMouseClicked(evt);
            }
        });
        jPanel1.add(jBtn_AtenderSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 50));

        jLbl_PacientesRestantes.setText("Pacientes por atender: 0");
        jPanel1.add(jLbl_PacientesRestantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jTxtArea_Pacientes.setColumns(20);
        jTxtArea_Pacientes.setRows(5);
        jScrollPane1.setViewportView(jTxtArea_Pacientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, 460));

        jLbl_PacientesAtendidos.setText("Pacientes Atendidos");
        jPanel1.add(jLbl_PacientesAtendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_AtenderSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_AtenderSiguienteMouseClicked
        if(queue.size() > 0)
        {
            CPaciente p = queue.remove();
            jTxtArea_Pacientes.append(p.nombre + "," + p.sintoma + "," +
                    p.prioridad + "\n");
        }
    }//GEN-LAST:event_jBtn_AtenderSiguienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_AtenderSiguiente;
    private javax.swing.JLabel jLbl_PacientesAtendidos;
    private javax.swing.JLabel jLbl_PacientesRestantes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtArea_Pacientes;
    // End of variables declaration//GEN-END:variables
}
